# Copyright (c) Microsoft Corporation.
# Copyright (c) Soundscape Community Contributors.
# Licensed under the MIT License.

FROM python:3.12-slim-bookworm AS final

ENV PYTHONUNBUFFERED=true TILESRV=/tilesrv

COPY requirements.txt gentiles.py $TILESRV/

RUN python -m pip install --no-cache-dir -r $TILESRV/requirements.txt

ENTRYPOINT ["sh", "-c", "exec python /tilesrv/gentiles.py --verbose --dsn \"$DSN\""]
