# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    unlock_keychain
    increment_build_number(xcodeproj: "GuideDogs.xcodeproj")
    build_app(
      workspace: "GuideDogs.xcworkspace",
      scheme: "Openscape",
      output_name: "openscape.ipa",
      export_xcargs: "-allowProvisioningUpdates",
      clean: true
    )
    #upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Removes testers if they haven't launched the app in a month"
  lane :clean_testers do
    clean_testflight_testers
  end

  # To push new certificates to the repository (must have sufficient role in app store connect):
  # bundle exec fastlane match development
  # bundle exec fastlane match appstore

  desc "Retrieves and installs code signing certificates"
  lane:certs do
    unlock_keychain
    match(clone_branch_directly: true, readonly: true)
  end

end
