source 'https://rubygems.org'

gem 'cocoapods', '1.11.3'
gem 'cocoapods-patch', '1.0.2'
gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
