name: "build and submit to testflight"
on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/ios/**'
      - '.github/workflows/build-for-testflight.yml'
  workflow_dispatch:
jobs:
      runs-on: macos-14
    env:
      APP_SCHEME: Soundscape
      APP_PROJECT: apps/ios/GuideDogs.xcodeproj
      ARCHIVE_PATH: build/GuideDogs.xcarchive
      EXPORT_PLIST: build/ExportOptions.plist

    steps:
    # 1  Check out code with push permissions (needed for commit)
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    # 2  Increment the build number 
    - name: Bump build number
      run: agvtool bump 

    # 3  Commit and push the version change (avoid loop with [skip ci])
    - name: Commit bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "chore(ci): bump build number [skip ci]" || echo "Nothing to commit"
        git push

    # 4  Select the latest stable Xcode version 
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "latest-stable"

    # 5  Archive with the same automatic-signing settings Xcode’s Organiser uses
    - name: Archive project
      run: |
        xcodebuild \
          -project "$APP_PROJECT" \
          -scheme "$APP_SCHEME" \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -allowProvisioningUpdates \
          -apiKey    ${{ secrets.APPSTORE_API_KEY_ID }} \
          -apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }} \
          -archivePath "$ARCHIVE_PATH" \
          archive

    # 6  Generate the export options plist that “Distribute App → App Store” would create
    - name: Create export options
      run: |
        mkdir -p build
        cat > "$EXPORT_PLIST" <<'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key><string>app-store</string>
          <key>destination</key><string>upload</string>   <!-- Xcode 15+ uploads directly -->
          <key>signingStyle</key><string>automatic</string>
          <key>manageAppVersionAndBuildNumber</key><false/>
          <key>stripSwiftSymbols</key><true/>
          <key>uploadSymbols</key><true/>
        </dict>
        </plist>
        EOF

    # 7  Export and upload in one step (same as the Organiser “Upload” button)
    - name: Export & upload
      run: |
        xcodebuild -exportArchive \
          -archivePath "$ARCHIVE_PATH" \
          -exportOptionsPlist "$EXPORT_PLIST" \
          -allowProvisioningUpdates \
          -apiKey    ${{ secrets.APPSTORE_API_KEY_ID }} \
          -apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/MyApp.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build

    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v3
      with:
        app-path: build/MyApp.ipa
        api-key-id:     ${{ vars.APPSTORE_API_KEY_ID }}
        issuer-id:      ${{ vars.APPSTORE_ISSUER_ID }}
        api-private-key:${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        